# Generated by Django 5.2.8 on 2025-11-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget'),
        ('hr', '0005_alter_employee_options_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='hr.department'),
        ),
        migrations.AddField(
            model_name='budget',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Allocated Amount', max_digits=15),
        ),
    ]
