# Generated by Django 5.2.8 on 2026-01-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bankstatement_bankstatementline'),
        ('hr', '0008_applicant_employee_travelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vendor_suggestion', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ORDERED', 'Ordered')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to='hr.employee')),
                ('budget', models.ForeignKey(blank=True, help_text='Budget to charge against', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.budget')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='hr.employee')),
            ],
        ),
    ]
