# Generated by Django 5.2.8 on 2025-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PAYROLL_RUN', 'Payroll Run'), ('EMPLOYEE_HIRE', 'Employee Hire'), ('EMPLOYEE_TERMINATION', 'Employee Termination')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('AUDIT', 'Audit'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
