# Generated by Django 5.2.8 on 2025-11-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_employee_status_7e01e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_employee_hire_da_4d71d0_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
