# Generated by Django 5.2.6 on 2025-10-26 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('HR', 'Human Resources'), ('FINANCE', 'Finance')], max_length=20)),
                ('action_type', models.CharField(choices=[('PAYROLL_RUN', 'Payroll Run'), ('EMPLOYEE_HIRE', 'Employee Hire'), ('EMPLOYEE_TERMINATION', 'Employee Termination')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
