# Generated by Django 5.2.8 on 2026-01-09 19:19

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_changes_auditlog_model_name_and_more'),
        ('hr', '0007_performancegoal_performancereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('authority', models.CharField(help_text='e.g. IRS, GDPR, OSHA', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('control_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('DETECTIVE', 'Detective'), ('CORRECTIVE', 'Corrective')], max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('AD_HOC', 'Ad Hoc')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_owned', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ControlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PARTIAL', 'Partial')], max_length=10)),
                ('evidence', models.TextField(blank=True, help_text='Link or description of evidence', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_performed', to='hr.employee')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='audit.internalcontrol')),
            ],
        ),
    ]
