# Generated by Django 5.2.8 on 2026-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('HR', 'HR Admin'), ('FINANCE', 'Finance Admin'), ('AUDIT', 'Audit Admin'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
