# Generated by Django 5.2.8 on 2026-01-11 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_contact_invoice_invoiceitem_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(help_text='Statement Number/Ref', max_length=100)),
                ('start_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('end_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='GL Account (Bank)', limit_choices_to={'type': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for Deposit, Negative for Withdrawal', max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('matched_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_bank_line', to='finance.journalentry')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.bankstatement')),
            ],
        ),
    ]
