# Generated by Django 5.2.6 on 2025-10-26 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual'), ('INTERN', 'Intern')], default='PERMANENT', max_length=20)),
                ('hire_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True, verbose_name='KRA PIN')),
                ('nssf_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='NSSF Number')),
                ('SHA_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='SHA Number')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department')),
            ],
            options={
                'ordering': ['staff_number'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee'),
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('change_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('SALARY_INCREASE', 'Salary Increase'), ('SALARY_DECREASE', 'Salary Decrease'), ('DEMOTION', 'Demotion'), ('TERMINATION', 'Termination'), ('RESIGNATION', 'Resignation'), ('SUSPENSION', 'Suspension'), ('REINSTATEMENT', 'Reinstatement')], max_length=20)),
                ('previous_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('new_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='hr.employee')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_employees', to='hr.department')),
                ('previous_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_employees', to='hr.department')),
            ],
            options={
                'verbose_name_plural': 'Employment Histories',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(default=django.utils.timezone.now)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paye_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PAYE Tax')),
                ('nssf_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='NSSF Deduction')),
                ('sha_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SHA Deduction')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('POSTED', 'Posted to Finance'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('is_posted_to_finance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='hr.employee')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='finance.journalentry')),
            ],
            options={
                'ordering': ['-period_end', '-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('LOAN', 'Loan Repayment'), ('ADVANCE', 'Salary Advance'), ('INSURANCE', 'Insurance'), ('UNION_DUES', 'Union Dues'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_deductions', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['deduction_type'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'department'], name='hr_employee_status_7e01e4_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='hr_employee_hire_da_4d71d0_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['employee', '-effective_date'], name='hr_employme_employe_2858fb_idx'),
        ),
        migrations.AddIndex(
            model_name='employmenthistory',
            index=models.Index(fields=['change_type'], name='hr_employme_change__f32307_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['employee', '-period_end'], name='hr_payrollr_employe_22b3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status'], name='hr_payrollr_status_b89bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['pay_date'], name='hr_payrollr_pay_dat_84d5ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('employee', 'period_start', 'period_end')},
        ),
    ]
